### ISSUE TITLE
Pagination error

### ISSUE THREAD

**Issue by mtjon** [mobybit/hugo-natrium-theme#13]
Hi,

Just started looking at Hugo, liked your Natrium theme; appreciate its simplicity.

When cloning the theme into the `themes/`-dir, I get below error that seemingly has to do with pagination, however:

ERROR 2019/02/12 20:49:30 Failed to render pages: render of home failed: /home/usrname/git/hugo-blog/themes/hugo-natrium-theme/layouts/index.html:6:15: execute of template failed: template: index.html:6:15: executing index.html at <.Paginate>: error calling Paginate: cannot convert type hugolib.PagesGroup to Pages

I'm not familiar enough with Hugo to fix it myself, or I'd make a pull request.

# Hugo env

Hugo Static Site Generator v0.54.0-B1A82C61 linux/amd64 BuildDate: 2019-02-01T09:40:34Z
GOOS="linux"
GOARCH="amd64"
GOVERSION="go1.11.5"

# Hugo config

allthemes = [{Name:hugo-natrium-theme ConfigFilename: Cfg:<nil>}]
archetypedir = "archetypes"
assetdir = "assets"
baseurl = "http://localhost/"
blackfriday = &{Smartypants:true SmartypantsQuotesNBSP:false AngledQuotes:false Fractions:true HrefTargetBlank:false NofollowLinks:false NoreferrerLinks:false SmartDashes:true LatexDashes:true TaskLists:true PlainIDAnchors:true Extensions:[] ExtensionsMask:[]}
builddrafts = false
buildexpired = false
buildfuture = false
cachedir = "/tmp/hugo_cache/"
canonifyurls = false
cleandestinationdir = false
contentdir = "content"
datadir = "data"
debug = false
defaultcontentlanguage = "en"
defaultcontentlanguageinsubdir = false
disablealiases = false
disablefastrender = false
disablelivereload = false
disablepathtolower = false
enableemoji = false
enablegitinfo = false
enableinlineshortcodes = false
enablemissingtranslationplaceholders = false
environment = "production"
footnoteanchorprefix = ""
footnotereturnlinkcontents = ""
forcesyncstatic = false
hascjklanguage = false
i18ndir = "i18n"
ignorecache = false
ignorefiles = []
indexes = map[category:categories tag:tags]
languagecode = "en-us"
languagessorted = [en]
layoutdir = "layouts"
menus = map[main:[map[name:About url:/about/ weight:-110] map[name:Tags url:/tags weight:-120] map[name:Categories url:/categories weight:-130]]]
metadataformat = "toml"
multilingual = false
newcontenteditor = ""
paginate = 10
paginatepath = "page"
params = map[logo:map[width:50 alt:Logo url:logo.png height:50] description:]
permalinks = map[post:/:slug/ page:/:slug/]
pluralizelisttitles = true
preservetaxonomynames = true
publishdir = "public"
pygmentscodefences = true
pygmentscodefencesguesssyntax = false
pygmentsoptions = ""
pygmentsstyle = "native"
pygmentsuseclasses = false
pygmentsuseclassic = false
relativeurls = false
removepathaccents = false
resourcedir = "resources"
rsslimit = 10
sectionpagesmenu = ""
sitemap = {ChangeFreq: Priority:-1 Filename:sitemap.xml}
staticdir = "static"
summarylength = 70
taxonomies = map[category:categories tag:tags]
theme = "hugo-natrium-theme"
themesdir = "themes"
timeout = 10000
title = "Natrium Theme"
titlecasestyle = "AP"
uglyurls = false
verbose = false
watch = false
workingdir = "/home/mnmt/git/hugo-blog"

# Steps to reproduce

```
cd $(mktemp -d)
hugo new site .
git clone git@github.com:mobybit/hugo-natrium-theme.git themes/hugo-natrium-theme
```
Edit the `config.toml` to refer to the theme, then `hugo serve`

**Comment by mobybit** [comment]
Thanks for reporting. I will look into it.

**Comment by codazoda** [comment]
I had the same error and was able to solve it. For me, it was related to the fact that I was using a `posts` folder instead of a `post` folder. You have two options to fix it. Rename your `posts` folder to `post` or edit the word `post` in the themes `index.html` file to `posts`. Here's the new line.

```
     {{ range (.Paginate ((where .Data.Pages "Type" "posts").GroupByDate "2006")).PageGroups }}
```

The official [quick start guide](https://gohugo.io/getting-started/quick-start/) suggests using the `posts` folder. Specifically, they suggest the following command.

```
hugo new posts/my-first-post.md
```

I submitted PR https://github.com/mobybit/hugo-natrium-theme/pull/14 to address the issue by editing the template to expect `/posts` instead of `/post`.
